export type Florist = {
  id: number
  status: string
  ref: string
  florist_name: string
  contact_number: string
  address: string
  city: string
  postcode: string
  call_outcome: string
  social_media_link: string
  product_type: string
  product_price: string
  delivery_fee: string
  sell_extras: string
  popularity_trend: string
  preferred_communication: string
  has_website: string
  member_of_other_networks: string
  flower_supplier: string
  interested_in_free_website: string
  discount_offer: null
  florist_rep: string
  additional_info: string | null
  floristcode: string
  photo: string | null
  description: string | null
  collections: string | null
  meta_description: string | null
  page_title: string | null
  photo_url: string | null
  province: string
  imported: number
  shopifyid: string
  listing_status: boolean | null
}

export const florists: Florist[] = [
  {
    "id": 1,
    "status": "New",
    "ref": "10001",
    "florist_name": "Jea's Flower Shop - Cebu",
    "contact_number": "9333491300",
    "address": "Mandaue City",
    "city": "Mandaue City",
    "postcode": "6014",
    "call_outcome": "Reached out via FB",
    "social_media_link": "https://www.facebook.com/jeasflowersandservices",
    "product_type": "6 Red Roses",
    "product_price": "800 pesos for Cagayan rose with Gythso fillers, 1,",
    "delivery_fee": "Varried, they deliver through Grab, Maxim or Lalam",
    "sell_extras": "",
    "popularity_trend": "Yes.",
    "preferred_communication": "Phone",
    "has_website": "No",
    "member_of_other_networks": "No.",
    "flower_supplier": "Awaiting response",
    "interested_in_free_website": "Yes",
    "discount_offer": null,
    "florist_rep": "",
    "additional_info": "",
    "floristcode": "CEBJEA1",
    "photo": "CEBJEA1.jpg",
    "description": "",
    "collections": "",
    "meta_description": "",
    "page_title": "",
    "photo_url": "",
    "province": "Cebu",
    "imported": 1,
    "shopifyid": "0",
    "listing_status": null
  },
  {
    "id": 2,
    "status": "New",
    "ref": "10002",
    "florist_name": "Cora's Flowers And Giveaways",
    "contact_number": "9662191243",
    "address": "Interim 2nd unit new carbon market ,",
    "city": "Cebu City",
    "postcode": "6000",
    "call_outcome": "Reached out via FB",
    "social_media_link": "https://www.facebook.com/profile.php?id=100084786107509",
    "product_type": "6 Red Roses",
    "product_price": "400 pesos with golden rod fillers ",
    "delivery_fee": "100 pesos within the city only, additional fee if ",
    "sell_extras": "",
    "popularity_trend": "Yes.",
    "preferred_communication": "Phone",
    "has_website": "No",
    "member_of_other_networks": "No.",
    "flower_supplier": "Not willing to disclose specifics she only said they will always have a supply so we don't need to worry about that. ",
    "interested_in_free_website": "Yes",
    "discount_offer": null,
    "florist_rep": "",
    "additional_info": "",
    "floristcode": "CEBCOR2",
    "photo": "CEBCOR2.jpg",
    "description": "",
    "collections": "",
    "meta_description": "",
    "page_title": "",
    "photo_url": "",
    "province": "Cebu",
    "imported": 1,
    "shopifyid": "0",
    "listing_status": null
  },
  {
    "id": 3,
    "status": "New",
    "ref": "10003",
    "florist_name": "Rose's Flower Shop",
    "contact_number": "9323099928",
    "address": "Interim building carbon market flower 13",
    "city": "Cebu City",
    "postcode": "6000",
    "call_outcome": "Call was dropped, No response on FB",
    "social_media_link": "https://www.facebook.com/groups/616245875560858/user/100007707937946/",
    "product_type": "Mixed Pastel Bouquet",
    "product_price": "Not Interested. ",
    "delivery_fee": "Not Interested. ",
    "sell_extras": "",
    "popularity_trend": "Not Interested. ",
    "preferred_communication": "",
    "has_website": "",
    "member_of_other_networks": "Not Interested. ",
    "flower_supplier": "Not Interested. ",
    "interested_in_free_website": "",
    "discount_offer": null,
    "florist_rep": "",
    "additional_info": null,
    "floristcode": "CEBROS3",
    "photo": null,
    "description": null,
    "collections": null,
    "meta_description": null,
    "page_title": null,
    "photo_url": null,
    "province": "Cebu",
    "imported": 1,
    "shopifyid": "0",
    "listing_status": null
  },
  {
    "id": 4,
    "status": "New",
    "ref": "10004",
    "florist_name": "Hayag Flower Shop",
    "contact_number": "9429503157",
    "address": "",
    "city": "Cebu City",
    "postcode": "6000",
    "call_outcome": "Reached out via FB",
    "social_media_link": "https://www.facebook.com/profile.php?id=100063598554422",
    "product_type": "Mixed Pastel Bouquet",
    "product_price": "800-2,500 depending on the number of flowers and t",
    "delivery_fee": "Varried, depending on the location. ",
    "sell_extras": "",
    "popularity_trend": "Yes.",
    "preferred_communication": "Phone",
    "has_website": "No",
    "member_of_other_networks": "No. ",
    "flower_supplier": "Cannot disclose on the matter. He said they have various suppliers.",
    "interested_in_free_website": "",
    "discount_offer": null,
    "florist_rep": "",
    "additional_info": null,
    "floristcode": "CEBHAY4",
    "photo": "CEBHAY4.jpg",
    "description": null,
    "collections": null,
    "meta_description": null,
    "page_title": null,
    "photo_url": null,
    "province": "Cebu",
    "imported": 1,
    "shopifyid": "0",
    "listing_status": null
  },
  {
    "id": 5,
    "status": "New",
    "ref": "10005",
    "florist_name": "Cebu Affordable Bouquet And Gifts",
    "contact_number": "9532694252",
    "address": "Mj cuenco ave",
    "city": "Cebu City",
    "postcode": "6000",
    "call_outcome": "Reached out via FB",
    "social_media_link": "https://www.facebook.com/yhanzbouquetandgiftshop",
    "product_type": "Gebera",
    "product_price": "2,000 - for 10pcs. Gerbera pink,10pcs gerbera whit",
    "delivery_fee": "150 pesos (minimum for inhouse driver) but they al",
    "sell_extras": "",
    "popularity_trend": "Yes.",
    "preferred_communication": "Phone",
    "has_website": "",
    "member_of_other_networks": "They were before, but now they are not part of any networks. They don't know any details of the network except they were based in Manila.",
    "flower_supplier": "Not willing to disclose the specifics, she mentioned they source them locally and some flowers are sourced internationally too. ",
    "interested_in_free_website": "",
    "discount_offer": null,
    "florist_rep": "",
    "additional_info": null,
    "floristcode": "CEBCEB5",
    "photo": "CEBCEB5.jpg",
    "description": null,
    "collections": null,
    "meta_description": null,
    "page_title": null,
    "photo_url": null,
    "province": "Cebu",
    "imported": 1,
    "shopifyid": "0",
    "listing_status": null
  },
  {
    "id": 6,
    "status": "New",
    "ref": "10006",
    "florist_name": "Flower Bar Cebu",
    "contact_number": "9173053194",
    "address": "Unit 2 Carbon Market, Ermita",
    "city": "Cebu City",
    "postcode": "6000",
    "call_outcome": "Called via phone",
    "social_media_link": "https://www.facebook.com/profile.php?id=61552232589488",
    "product_type": "Gebera",
    "product_price": "500-600 local gerbera 6 stems, 800-1000 imported G",
    "delivery_fee": "Varried - Lalamove only.",
    "sell_extras": "",
    "popularity_trend": "Yes.",
    "preferred_communication": "Phone",
    "has_website": "",
    "member_of_other_networks": "No. ",
    "flower_supplier": "Awaiting response",
    "interested_in_free_website": "",
    "discount_offer": null,
    "florist_rep": "",
    "additional_info": null,
    "floristcode": "CEBFLO6",
    "photo": "CEBFLO6.jpg",
    "description": null,
    "collections": null,
    "meta_description": null,
    "page_title": null,
    "photo_url": null,
    "province": "Cebu",
    "imported": 1,
    "shopifyid": "0",
    "listing_status": null
  },
  {
    "id": 7,
    "status": "New",
    "ref": "10007",
    "florist_name": "El Maria's Real Flowers - Cebu",
    "contact_number": "9152981921",
    "address": "",
    "city": "Cebu City",
    "postcode": "6000",
    "call_outcome": "Call was dropped, No response on FB either",
    "social_media_link": "https://www.facebook.com/profile.php?id=100084652668749",
    "product_type": "Mixed Rose Bouquet",
    "product_price": "Not Interested. ",
    "delivery_fee": "Not Interested. ",
    "sell_extras": "",
    "popularity_trend": "Not Interested. ",
    "preferred_communication": "",
    "has_website": "",
    "member_of_other_networks": "Not Interested. ",
    "flower_supplier": "Not Interested. ",
    "interested_in_free_website": "",
    "discount_offer": null,
    "florist_rep": "",
    "additional_info": null,
    "floristcode": "CEBELM7",
    "photo": "CEBELM7.jpg",
    "description": null,
    "collections": null,
    "meta_description": null,
    "page_title": null,
    "photo_url": null,
    "province": "Cebu",
    "imported": 1,
    "shopifyid": "0",
    "listing_status": null
  },
  {
    "id": 8,
    "status": "New",
    "ref": "10008",
    "florist_name": "Love Flowers And Gift Shop, Consolacion Cebu",
    "contact_number": "9215502614",
    "address": "CityMall Consolacion",
    "city": "Cebu City",
    "postcode": "6000",
    "call_outcome": "Reached out via FB",
    "social_media_link": "https://www.facebook.com/lavzgemps",
    "product_type": "Mixed Rose Bouquet",
    "product_price": "1,500 for a dozen-stem arrangement. ",
    "delivery_fee": "100 pesos within the city. ",
    "sell_extras": "",
    "popularity_trend": "Yes.",
    "preferred_communication": "",
    "has_website": "",
    "member_of_other_networks": "They are part of an association, World Florists Association and they do orders internationally too. ",
    "flower_supplier": "She mentioned they source their imported fillers and flowers in China, some from Baguio, some from local farmers in Cebu and Cagayan.",
    "interested_in_free_website": "",
    "discount_offer": null,
    "florist_rep": "",
    "additional_info": null,
    "floristcode": "CEBLOV8",
    "photo": "CEBLOV8.jpg",
    "description": null,
    "collections": null,
    "meta_description": null,
    "page_title": null,
    "photo_url": null,
    "province": "Cebu",
    "imported": 1,
    "shopifyid": "0",
    "listing_status": null
  },
  {
    "id": 9,
    "status": "New",
    "ref": "10009",
    "florist_name": "Cb's Online Flowershop Cebu",
    "contact_number": "9285867127",
    "address": "Cebu Transcentral Hwy",
    "city": "Cebu City",
    "postcode": "6000",
    "call_outcome": "Called via phone",
    "social_media_link": "https://www.facebook.com/profile.php?id=100063583284021",
    "product_type": "Sunflower Bouquet",
    "product_price": "1,800 for 4 sunflowers, 500 for 1 sunflower only. ",
    "delivery_fee": "100 pesos within the city. ",
    "sell_extras": "",
    "popularity_trend": "Yes.",
    "preferred_communication": "Facebook",
    "has_website": "",
    "member_of_other_networks": "Yes - they are part of a network but they can still take orders from us. ",
    "flower_supplier": "Customer cannot disclose on the matter, though over the phone I remember her saying she sources their flowers from a supplier in Carbon Market. ",
    "interested_in_free_website": "",
    "discount_offer": null,
    "florist_rep": "",
    "additional_info": null,
    "floristcode": "CEBCBS9",
    "photo": "CEBCBS9.jpg",
    "description": null,
    "collections": null,
    "meta_description": null,
    "page_title": null,
    "photo_url": null,
    "province": "Cebu",
    "imported": 1,
    "shopifyid": "0",
    "listing_status": null
  },
  {
    "id": 10,
    "status": "New",
    "ref": "10010",
    "florist_name": "Tip-Top Petals In Cebu",
    "contact_number": "9324229209",
    "address": "Carbon Market Interim Building",
    "city": "Cebu City",
    "postcode": "6000",
    "call_outcome": "Reached out via FB",
    "social_media_link": "https://www.facebook.com/profile.php?id=100079124254698",
    "product_type": "Sunflower Bouquet",
    "product_price": "1,800 for an arrangment with 4 sunflowers, their p",
    "delivery_fee": "100 to 150 maam, free delivery for orders 2,000 or",
    "sell_extras": "",
    "popularity_trend": "Yes.",
    "preferred_communication": "Phone",
    "has_website": "",
    "member_of_other_networks": "They were part of FlowerChimp before but they are focusing on local event orders now. ",
    "flower_supplier": "She did not answer my question, instead she asked if we had a Facebook page. I routed her to our page and she stopped responding since. ",
    "interested_in_free_website": "",
    "discount_offer": null,
    "florist_rep": "",
    "additional_info": null,
    "floristcode": "CEBTIP10",
    "photo": "CEBTIP10.jpg",
    "description": null,
    "collections": null,
    "meta_description": null,
    "page_title": null,
    "photo_url": null,
    "province": "Cebu",
    "imported": 1,
    "shopifyid": "0",
    "listing_status": null
  },
  {
    "id": 11,
    "status": "New",
    "ref": "10011",
    "florist_name": "CJ's Flowers Shop",
    "contact_number": "9761325352",
    "address": "Sampaloc Street",
    "city": "Manila",
    "postcode": "1008",
    "call_outcome": "Reached out via FB",
    "social_media_link": "https://www.facebook.com/profile.php?id=61550810016558",
    "product_type": "6 Red Roses",
    "product_price": "1,500 pesos. They only do a minimum of 12 roses pe",
    "delivery_fee": "Varried - Lalamove only.",
    "sell_extras": "",
    "popularity_trend": "Yes.",
    "preferred_communication": "Facebook",
    "has_website": "",
    "member_of_other_networks": "No. ",
    "flower_supplier": "Awaiting response",
    "interested_in_free_website": "",
    "discount_offer": null,
    "florist_rep": "",
    "additional_info": null,
    "floristcode": "MANCJS11",
    "photo": "MANCJS11.jpg",
    "description": null,
    "collections": null,
    "meta_description": null,
    "page_title": null,
    "photo_url": null,
    "province": "Metro Manila",
    "imported": 1,
    "shopifyid": "0",
    "listing_status": null
  },
  {
    "id": 12,
    "status": "New",
    "ref": "10012",
    "florist_name": "Jonel's Flower",
    "contact_number": "9127006044",
    "address": "Ma.Clara St. Sampaloc",
    "city": "Manila",
    "postcode": "1008",
    "call_outcome": "Reached out via FB",
    "social_media_link": "https://www.facebook.com/profile.php?id=100076630903522",
    "product_type": "6 Red Roses",
    "product_price": "650 pesos for 6 red roses in a bouquet, with babys",
    "delivery_fee": "Varried - They deliver through Lalamove.",
    "sell_extras": "",
    "popularity_trend": "Yes.",
    "preferred_communication": "Phone",
    "has_website": "",
    "member_of_other_networks": "Yes - they are part of a network but they can still take orders from us.",
    "flower_supplier": "They source them locally as they are located in the flower capital of NCR but no specifics.",
    "interested_in_free_website": "",
    "discount_offer": null,
    "florist_rep": "",
    "additional_info": null,
    "floristcode": "MANJON12",
    "photo": "MANJON12.jpg",
    "description": null,
    "collections": null,
    "meta_description": null,
    "page_title": null,
    "photo_url": null,
    "province": "Metro Manila",
    "imported": 1,
    "shopifyid": "0",
    "listing_status": null
  },
  {
    "id": 13,
    "status": "New",
    "ref": "10013",
    "florist_name": "Marky Olimpiada Boquet And Flowers",
    "contact_number": "9984067706",
    "address": "",
    "city": "Manila",
    "postcode": "1008",
    "call_outcome": "Reached out via FB",
    "social_media_link": "https://www.facebook.com/profile.php?id=100064190737866",
    "product_type": "Mixed Pastel Bouquet",
    "product_price": "1800 per 2 dozen stems, that's their minimum.",
    "delivery_fee": "200 pesos minimum",
    "sell_extras": "",
    "popularity_trend": "Yes.",
    "preferred_communication": "Facebook",
    "has_website": "No",
    "member_of_other_networks": "No.",
    "flower_supplier": "Awaiting response",
    "interested_in_free_website": "",
    "discount_offer": null,
    "florist_rep": "",
    "additional_info": null,
    "floristcode": "MANMAR13",
    "photo": "MANMAR13.jpg",
    "description": null,
    "collections": null,
    "meta_description": null,
    "page_title": null,
    "photo_url": null,
    "province": "Metro Manila",
    "imported": 1,
    "shopifyid": "0",
    "listing_status": null
  },
  {
    "id": 14,
    "status": "New",
    "ref": "10014",
    "florist_name": "Bunny Flowers Beutique",
    "contact_number": "9052923545",
    "address": "1152 dos castillias sampaloc ,,",
    "city": "Manila",
    "postcode": "1152",
    "call_outcome": "Reached out via FB",
    "social_media_link": "https://www.facebook.com/babiesflow",
    "product_type": "Mixed Pastel Bouquet",
    "product_price": "1,800 per 20 stems or pastel carnations, 2 colors.",
    "delivery_fee": "Varried - Lalamove only.",
    "sell_extras": "",
    "popularity_trend": "Yes.",
    "preferred_communication": "",
    "has_website": "No",
    "member_of_other_networks": "No.",
    "flower_supplier": "Awaiting response",
    "interested_in_free_website": "",
    "discount_offer": null,
    "florist_rep": "",
    "additional_info": null,
    "floristcode": "MANBUN14",
    "photo": "MANBUN14.jpg",
    "description": null,
    "collections": null,
    "meta_description": null,
    "page_title": null,
    "photo_url": null,
    "province": "Metro Manila",
    "imported": 1,
    "shopifyid": "0",
    "listing_status": null
  },
  {
    "id": 15,
    "status": "New",
    "ref": "10015",
    "florist_name": "Yoohhann Flower Shop",
    "contact_number": "9618977630",
    "address": "1560 maria Clara st sta Cruz 1014",
    "city": "Manila",
    "postcode": "1014",
    "call_outcome": "Reached out via FB",
    "social_media_link": "https://www.facebook.com/Rodriguezpheejhay",
    "product_type": "Gebera",
    "product_price": "800 pesos for 10 pieces of local gerbera (1 color)",
    "delivery_fee": "Varried - Lalamove only.",
    "sell_extras": "",
    "popularity_trend": "Yes.",
    "preferred_communication": "Facebook",
    "has_website": "No",
    "member_of_other_networks": "No. ",
    "flower_supplier": "Not willing to disclose this information. ",
    "interested_in_free_website": "",
    "discount_offer": null,
    "florist_rep": " and stopped responding after. \"",
    "additional_info": null,
    "floristcode": "MANYOO15",
    "photo": "MANYOO15.jpg",
    "description": null,
    "collections": null,
    "meta_description": null,
    "page_title": null,
    "photo_url": null,
    "province": "Metro Manila",
    "imported": 1,
    "shopifyid": "0",
    "listing_status": null
  },
  {
    "id": 17,
    "status": "New",
    "ref": "10017",
    "florist_name": "Chachi's Bouquet",
    "contact_number": "9066696526",
    "address": "España Blvd, Sampaloc",
    "city": "Manila",
    "postcode": "1008",
    "call_outcome": "Call was dropped, No response on FB either",
    "social_media_link": "https://www.facebook.com/profile.php?id=100092582213490",
    "product_type": "Mixed Rose Bouquet",
    "product_price": "Not Interested. ",
    "delivery_fee": "Not Interested. ",
    "sell_extras": "",
    "popularity_trend": "Not Interested. ",
    "preferred_communication": "",
    "has_website": "",
    "member_of_other_networks": "Not Interested. ",
    "flower_supplier": "Not Interested. ",
    "interested_in_free_website": "",
    "discount_offer": null,
    "florist_rep": "",
    "additional_info": null,
    "floristcode": "MANCHA17",
    "photo": "MANCHA17.jpg",
    "description": null,
    "collections": null,
    "meta_description": null,
    "page_title": null,
    "photo_url": null,
    "province": "Metro Manila",
    "imported": 1,
    "shopifyid": "0",
    "listing_status": null
  },
  {
    "id": 18,
    "status": "New",
    "ref": "10018",
    "florist_name": "SP Bloom Flower Shop",
    "contact_number": "9654998151",
    "address": "Maria Clara Street 1008 ,",
    "city": "Manila",
    "postcode": "1008",
    "call_outcome": "Reached out via FB",
    "social_media_link": "https://www.facebook.com/profile.php?id=61550632611843",
    "product_type": "Mixed Rose Bouquet",
    "product_price": "1,000 pesos for 24 pieces, but canot guarantee if ",
    "delivery_fee": "100 pesos minimum, within the area only. ",
    "sell_extras": "",
    "popularity_trend": "Yes.",
    "preferred_communication": "Facebook",
    "has_website": "No",
    "member_of_other_networks": "No.",
    "flower_supplier": "No response, the florist only seen-zoned my last message. ",
    "interested_in_free_website": "",
    "discount_offer": null,
    "florist_rep": "",
    "additional_info": null,
    "floristcode": "MANSPB18",
    "photo": "MANSPB18.jpg",
    "description": null,
    "collections": null,
    "meta_description": null,
    "page_title": null,
    "photo_url": null,
    "province": "Metro Manila",
    "imported": 1,
    "shopifyid": "0",
    "listing_status": null
  },
  {
    "id": 19,
    "status": "New",
    "ref": "10019",
    "florist_name": "Joanna's Design Flowershop",
    "contact_number": "9065171124",
    "address": "1302 dos castillas st sampaloc",
    "city": "Manila",
    "postcode": "3100",
    "call_outcome": "Call was dropped, No response on FB either",
    "social_media_link": "https://www.facebook.com/jakearucanan",
    "product_type": "Sunflower Bouquet",
    "product_price": "Not Interested. ",
    "delivery_fee": "Not Interested. ",
    "sell_extras": "",
    "popularity_trend": "Not Interested. ",
    "preferred_communication": "",
    "has_website": "",
    "member_of_other_networks": "Not Interested. ",
    "flower_supplier": "Not Interested. ",
    "interested_in_free_website": "",
    "discount_offer": null,
    "florist_rep": "",
    "additional_info": null,
    "floristcode": "MANJOA19",
    "photo": "MANJOA19.jpg",
    "description": null,
    "collections": null,
    "meta_description": null,
    "page_title": null,
    "photo_url": null,
    "province": "Metro Manila",
    "imported": 1,
    "shopifyid": "0",
    "listing_status": null
  },
  {
    "id": 20,
    "status": "New",
    "ref": "10020",
    "florist_name": "Five Angels Flower Shop",
    "contact_number": "9063846395",
    "address": "Dos Castillas St.",
    "city": "Manila",
    "postcode": "1008",
    "call_outcome": "Reached out via FB",
    "social_media_link": "https://www.facebook.com/FiveAngelsFlowershop",
    "product_type": "Sunflower Bouquet",
    "product_price": "1,500 for a 4-stem arrangement of sunflowers, pric",
    "delivery_fee": "200 minimum delivery fee.",
    "sell_extras": "",
    "popularity_trend": "Yes.",
    "preferred_communication": "Phone",
    "has_website": "No",
    "member_of_other_networks": "Yes but only through local entities that market their flowers through facebook and pass the orders to them.",
    "flower_supplier": "No response, florist said they are too busy right now. ",
    "interested_in_free_website": "",
    "discount_offer": null,
    "florist_rep": "",
    "additional_info": null,
    "floristcode": "MANFIV20",
    "photo": "MANFIV20.jpg",
    "description": null,
    "collections": null,
    "meta_description": null,
    "page_title": null,
    "photo_url": null,
    "province": "Metro Manila",
    "imported": 1,
    "shopifyid": "0",
    "listing_status": null
  },
  {
    "id": 21,
    "status": "New",
    "ref": "10021",
    "florist_name": "Tagbilaran Flowers & Gifts Surprised Delivery",
    "contact_number": "9854983698",
    "address": "J.A Clarin St",
    "city": "Tagbilaran City",
    "postcode": "6300",
    "call_outcome": "Reached out via FB",
    "social_media_link": "https://www.facebook.com/kaluhasflowershopjagna",
    "product_type": "6 Red Roses",
    "product_price": "1,200 for 12 red roses, minimum. However, the pric",
    "delivery_fee": "Free delivery within Tagbilaran City",
    "sell_extras": "Yes",
    "popularity_trend": "Yes.",
    "preferred_communication": "Facebook",
    "has_website": "No",
    "member_of_other_networks": "No. ",
    "flower_supplier": "Not willing to share this information.",
    "interested_in_free_website": "",
    "discount_offer": null,
    "florist_rep": "",
    "additional_info": null,
    "floristcode": "TAGTAG21",
    "photo": "TAGTAG21.jpg",
    "description": null,
    "collections": null,
    "meta_description": null,
    "page_title": null,
    "photo_url": null,
    "province": "Bohol",
    "imported": 1,
    "shopifyid": "0",
    "listing_status": null
  }
]
